[[Gmsh_SDK]]
arch = "x86_64"
git-tree-sha1 = "cf8d39eb4db785726c3fd00d24bf53747b7c730b"
os = "macos"

    [[Gmsh_SDK.download]]
    sha256 = "a6c49b5bd2fffa1d1f889a0791e91be93cfbacac65f3e1226905c8ca9ea007a0"
    url = "https://github.com/shipengcheng1230/Gmsh_SDK_jll.jl/releases/download/Gmsh_SDK-v4.6.0+0/Gmsh_SDK.v4.6.0.x86_64-apple-darwin14.tar.gz"
[[Gmsh_SDK]]
arch = "x86_64"
git-tree-sha1 = "536cc7f40eb512f33182664e5ef604c1bce2cd0e"
libc = "glibc"
os = "linux"

    [[Gmsh_SDK.download]]
    sha256 = "2c554a4afc4841853b6e9dbe1d255c890bbf809f059d387a119f9e3b520bf719"
    url = "https://github.com/shipengcheng1230/Gmsh_SDK_jll.jl/releases/download/Gmsh_SDK-v4.6.0+0/Gmsh_SDK.v4.6.0.x86_64-linux-gnu.tar.gz"
[[Gmsh_SDK]]
arch = "x86_64"
git-tree-sha1 = "09142e3056b4a2e99da4c2d26dc9ab38948faf0c"
os = "windows"

    [[Gmsh_SDK.download]]
    sha256 = "ac1c21a0f3ff8c83e368ae94f7cf41570dff7946e083f0a3ed5e42b962515fed"
    url = "https://github.com/shipengcheng1230/Gmsh_SDK_jll.jl/releases/download/Gmsh_SDK-v4.6.0+0/Gmsh_SDK.v4.6.0.x86_64-w64-mingw32.tar.gz"
