# Autogenerated wrapper script for Gmsh_SDK_jll for x86_64-w64-mingw32
export libgmsh

## Global variables
PATH = ""
LIBPATH = ""
LIBPATH_env = "PATH"
LIBPATH_default = ""

# Relative path to `libgmsh`
const libgmsh_splitpath = ["bin", "libgmsh.dll"]

# This will be filled out by __init__() for all products, as it must be done at runtime
libgmsh_path = ""

# libgmsh-specific global declaration
# This will be filled out by __init__()
libgmsh_handle = C_NULL

# This must be `const` so that we can use it with `ccall()`
const libgmsh = "libgmsh.dll"


"""
Open all libraries
"""
function __init__()
    global artifact_dir = abspath(artifact"Gmsh_SDK")

    # Initialize PATH and LIBPATH environment variable listings
    global PATH_list, LIBPATH_list
    global libgmsh_path = normpath(joinpath(artifact_dir, libgmsh_splitpath...))

    # Manually `dlopen()` this right now so that future invocations
    # of `ccall` with its `SONAME` will find this path immediately.
    global libgmsh_handle = dlopen(libgmsh_path)
    push!(LIBPATH_list, dirname(libgmsh_path))

    # Filter out duplicate and empty entries in our PATH and LIBPATH entries
    filter!(!isempty, unique!(PATH_list))
    filter!(!isempty, unique!(LIBPATH_list))
    global PATH = join(PATH_list, ';')
    global LIBPATH = join(vcat(LIBPATH_list, [Sys.BINDIR, joinpath(Sys.BINDIR, Base.LIBDIR, "julia"), joinpath(Sys.BINDIR, Base.LIBDIR)]), ';')
end  # __init__()

